# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-09-02 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('suite', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('zipcode', models.CharField(max_length=50, verbose_name='Индекс')),
                ('lat', models.CharField(max_length=40, verbose_name='Широта')),
                ('lng', models.CharField(max_length=40, verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('cathPhrase', models.CharField(max_length=500, verbose_name='Слоган')),
                ('bs', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Логин')),
                ('email', models.CharField(max_length=40, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('website', models.CharField(max_length=100, verbose_name='Сайт')),
                ('addres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='post.Addres')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='post.Company')),
            ],
        ),
    ]
